# Java ????????????
org.gradle.java.home=/home/meg8egb/.sdkman/candidates/java/25.0.1-tem

# Kotlin ????????????
kotlin.code.style=official
kotlin.jvm.target.validation.mode=ignore

# Gradle ???????????
org.gradle.caching=false  # ???????? ????????? ???
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.configureondemand=true

# ????????? ?????????? ????
org.gradle.configuration-cache=false
org.gradle.unsafe.configuration-cache=false
org.gradle.unsafe.isolated-projects=false

# ??? Spring Boot
org.gradle.jvmargs=-Xmx2g -Xms256m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8